# Settings
url: https://wfaquieri.github.io
baseurl: 
title: Portfólio de Projetos
tagline: de Ciência de Dados
bannerTitle: "Winicius Faquieri"
bannerTagline: Data Scientist @FGV IBRE
bannerDescription: Sou um cientista de dados com formação em economia e habilidades avançadas em técnicas de Data Science, incluindo Machine Learning e Inteligência Artificial. Possuo mais de 4 anos de experiência em solução de problemas de negócios por meio da aplicação dessas técnicas, liderando e participando de projetos na FGV-IBRE. Além disso, possuo mestrado em economia com ênfase em métodos quantitativos e pós-graduação em Inteligência Artificial, Machine Learning e Deep Learning pelo INFNET. 
bannerImage: images/profile-test.jpg
bannerButton: true
bannerButtonLink: index.html
contactTagline: Quer trabalhar juntos em um projeto? Entre em contato!
copyright: Copyright © 2022 Winicius Faquieri

# Featurette
featuretteTitle: Skills
featuretteFirstHighlight: Python e R
featuretteFirstTagline: Conhecimento avançado em programação em Python e R para análise de dados, modelagem estatística e aprendizado de máquina.
featuretteFirstIcon: icon fa-code
featuretteSecondHighlight: Banco de Dados e SQL
featuretteSecondTagline: Experiência em gerenciamento de bancos de dados relacionais e não relacionais, bem como em escrever consultas SQL complexas para extrair informações úteis.
featuretteSecondIcon: icon fa-database
featuretteThirdHighlight: Visualização de Dados
featuretteThirdTagline: Habilidade em criar gráficos e visualizações de dados interativos para comunicar insights e resultados de análise de dados de forma eficaz.
featuretteThirdIcon: icon fa-bar-chart
featuretteFourthHighlight: Big Data e Nuvem
featuretteFourthTagline: Conhecimento de ferramentas e tecnologias para lidar com grandes conjuntos de dados, incluindo Hadoop, Spark, AWS e GCP.
featuretteFourthIcon: icon fa-cloud

# Contact
email: wfaquieri@gmail.com
phone: (21) 97630-2390
linkedin: https://www.linkedin.com/in/wfaquieri/
github: wfaquieri