# Settings
url: https://wfaquieri.github.io
baseurl: 
title: Portfólio de Projetos
tagline: de Ciência de Dados
bannerTitle: "Winicius Faquieri"
bannerTagline: Data Scientist @FGV IBRE
bannerDescription: Sou economista com mais de 4 anos de experiência em aplicação de técnicas avançadas de Data Science, como Machine Learning e Inteligência Artificial, em solução de problemas de negócios. Na FGV-IBRE, tenho liderado e participado de projetos de DS, aplicando minhas habilidades em linguagens como R, Python, SQL para resolver problemas complexos. Possuo conhecimento avançado em Shiny para a construção de aplicativos web e interesse em estudos na área de engenharia de software. 
bannerImage: images/foto2.jpg
bannerButton: true
bannerButtonLink: index.html
contactTagline: Quer trabalhar juntos em um projeto? Entre em contato!
copyright: Copyright © 2022 Winicius Faquieri

# Featurette
featuretteTitle: Skills
featuretteFirstHighlight: Python e R
featuretteFirstTagline: Conhecimento avançado em programação em Python e R para análise de dados, modelagem estatística e aprendizado de máquina. Tools - Tidyverse, NumPy, Pandas, Scikit-learn, XGBoost, Tidymodels, PyCaret.
featuretteFirstIcon: icon fa-code
featuretteSecondHighlight: Banco de Dados e SQL
featuretteSecondTagline: Experiência em gerenciamento de bancos de dados relacionais e não relacionais, bem como em escrever consultas SQL complexas para extrair informações úteis. Tools - PostgreSQL, PgAdmin 4, BigQuery, SQL Server.
featuretteSecondIcon: icon fa-database
featuretteThirdHighlight: Visualização de Dados
featuretteThirdTagline: Habilidade em criar gráficos e visualizações de dados interativos para comunicar insights e resultados de análise de dados de forma eficaz. Tools - ggplot2, echarts, shiny, seaborn, matplotlib, Power BI.
featuretteThirdIcon: icon fa-chart-bar
featuretteFourthHighlight: Engenharia de Machine Learning
featuretteFourthTagline: Conhecimento de ferramentas e tecnologias para criar, implementar e manter modelos de Machine Learning escaláveis e de alto desempenho. Tools - MLflow, Kedro, AutoML, Hugging Face.
featuretteFourthIcon: icon fa-gears
featuretteFifthHighlight: Comunicação
featuretteFifthTagline: Habilidade em comunicar os insights gerados de forma clara e objetiva, para que os stakeholders possam tomar decisões com base nas análises realizadas. 
featuretteFifthIcon: icon fa-comments
featuretteSixthHighlight: Pensamento crítico
featuretteSixthTagline: Pensamento crítico e criativo para solucionar problemas e encontrar insights relevantes a partir dos dados.
featuretteSixthIcon: icon fa-brain
featuretteSeventhHighlight: Conhecimento em negócios
featuretteSeventhTagline: Capacidade de entendimento do negócio para qaplicar as análises e insights de forma estratégica e contribuir para o sucesso da empresa.
featuretteSeventhIcon: icon fa-briefcase

# Contact
email: wfaquieri@gmail.com
phone: 
linkedin: wfaquieri
github: wfaquieri